pipeline {
    agent any
    environment {
        DOCKER_PASSWORD = credentials("docker_password")
        GITHUB_TOKEN = credentials("github_token")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }
        stage('Tag image') {
            steps {
                script {
                    
                    env.IMAGE_TAG = "${env.MAJOR_VERSION}.\$((${env.MINOR_VERSION} + 1)).${env.PATCH_VERSION}"
                    echo "IMAGE_TAG: ${env.IMAGE_TAG}"
                }
                echo "Echo is working"
                sh "docker build -t radumirigel/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION} ."
                sh "docker login docker.io -u ${DOCKER_PASSWORD_USR} -p ${DOCKER_PASSWORD_PSW}"
                sh "docker push radumirigel/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION}"
                sh "git tag ${env.IMAGE_TAG}"
                sh "git push https://$GITHUB_TOKEN@github.com/radumirigel/service.git ${env.IMAGE_TAG}"
                sh "IMAGE_TAG=${env.IMAGE_TAG} docker-compose up -d hello mongo"
                echo "IMAGE_TAG: ${IMAGE_TAG}"
            }
        }
        stage('Compose image') {
            steps {
                sh "IMAGE_TAG=${env.IMAGE_TAG} docker-compose up -d hello mongo"
                echo "IMAGE_TAG: ${IMAGE_TAG}"
            }
        }
    }
    
    
}
